### ISSUE TITLE
NocodB not working with fresh install

### ISSUE THREAD

**Issue by jcf2108** [YunoHost-Apps/nocodb_ynh#113]
Hi,

I have a recent installation of Yunohost and I am experiencing a problem after installing NocoDB.
The installation goes correctly, but there are some warnings and NocoDB does not launch...

Here is the log: https://paste.yunohost.org/raw/avupuhimog

Does anyone have any knowledge of the problem?
Thanks you in advance!
J.C.

**Comment by tituspijean** [comment]
Don't paste the logs, paste the link to the logs. https://yunohost.org/fr/help-me#montrez-les-erreurs-et-le

**Comment by jcf2108** [comment]
Oops sorry, I put the link, in fact it’s better... Can you help me?

**Comment by tituspijean** [comment]
I have just tested installing on arm64 too, with no error. Closing this issue, feel free to reopen if needed.
