### ISSUE TITLE
Update Plz (to v0.84.6)

### ISSUE THREAD

**Issue by 0cwa** [YunoHost-Apps/nocodb_ynh#16]
[v0.84.6 fixes csv import,](https://docs.nocodb.com/releases#0.84.6) would be very helpful to have.

I tried looking at nocodb_ynh/conf/app.src to make a PR, but I couldn't figure out how you got SOURCE_URL.

**Comment by tituspijean** [comment]
The PR was already made... merely waiting for testing.
