### ISSUE TITLE
Data input returns a 404 error and data can't be saved

### ISSUE THREAD

**Issue by fabiomrbarbosa** [YunoHost-Apps/nocodb_ynh#2]
### Describe the bug

When I try to input any content in any field of a new row in a NocoDB table, I get a 404 error stating that the row could not be saved.

### Context

- Hardware: VPS bought online with Hetzner
- YunoHost version: 4.2.8.3
- I have access to my server: Through SSH and through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 0.9~ynh1

### Steps to reproduce

I installed NocoDB in a subdomain of my VPS's main domain.
I created a new project and added a new table in NocoDB's web frontend with a few fields including single line text, checkboxes, dates and rating.
Then I tried to input some data and every field returned the message "Failed to save row: 404 error".
Refreshing the page shows that no data was saved.
This issue occurs regardless of using a GraphQL or a REST project.

### Logs

Not applicable as Yunohost only created a log for the app installation process.

**Comment by tituspijean** [comment]
I cannot replicate your issue. You can find `nocodb`'s logs in `/var/log/nocodb/nocodb.log`, so you can run `tail /var/log/nocodb/nocodb.log -n 30` to get an idea of what NocoDB complains about while you try to add a row.

**Comment by tituspijean** [comment]
Closing due to lack of feedback. Feel free to reopen with the requested information. :)
