### ISSUE TITLE
Attachment not working

### ISSUE THREAD

**Issue by KvL159** [YunoHost-Apps/nocodb_ynh#72]
### Describe the bug

Attachment not working: e.g. images

### Context
- YunoHost version: Latest
- Using, or trying to install package version/branch: master

### Steps to reproduce

1. Create a new column as "Attachment"
2. Attach an image
3. It appears broken
4. After opening the image link from a right-click, it appears to point to HTTP://127.0.0.1:port/path/to/image

From this upstream feedback: https://github.com/nocodb/nocodb/issues/1051
It appears that the environment variable
 NC_PUBLIC_URL maybe not be set properly to point to the domain.

Also note that there are some updates available from upstream

**Comment by KvL159** [comment]
I tried to make that change on a private fork, however I couldn't finds a solution:
It needs to edit the file: https://github.com/YunoHost-Apps/nocodb_ynh/blob/testing/conf/env
And add `NC_PUBLIC_URL="domain"`
I couldn't find which variable to use to get the "domain", any ideas @tituspijean ?

**Comment by tituspijean** [comment]
It should be `__DOMAIN__`, it is automagi cally replaced by the value of `$domain` in the installation script.

**Comment by KvL159** [comment]
@tituspijean I made and tested the fix, please check the pull request!
Could you trigger the autoupdate ? The latest version is 104.X, thank you!

**Comment by KvL159** [comment]
Fixed in testing!
