### ISSUE TITLE
Attachments limited to 1mb

### ISSUE THREAD

**Issue by KvL159** [YunoHost-Apps/nocodb_ynh#76]
### Describe the bug

Attachment are limited to 1mb

### Context
- YunoHost version: Latest
- Using, or trying to install package version/branch: master

### Steps to reproduce

1. Attach an image or pdf over 1mb
2. Get error code 413

From this upstream feedback: https://github.com/nocodb/nocodb/discussions/1135
It appears that nginx limit needs to be updated in docker container ? I'm not familiar enough with docker to investigate further

**Comment by tituspijean** [comment]
This package does not rely on Docker.

**Comment by KvL159** [comment]
OK! I'll try to find a fix for this issue a bit later

**Comment by KvL159** [comment]
Fixed in testing!
