### ISSUE TITLE
Outdated version

### ISSUE THREAD

**Issue by KvL159** [YunoHost-Apps/nocodb_ynh#77]
### Describe the bug

The current master is 100.x and one branch is up to 101.x, the new available version is 104.x

### Context
- YunoHost version: Latest
- Using, or trying to install package version/branch: master or testing

### Steps to reproduce

1. Install the latest package
2. Version is 100.2

I saw that you created an autoupdater script, however it doesn't seem to be triggered since a couple of versions, could you check ? @tituspijean

**Comment by tituspijean** [comment]
Duplicate of #22.

**Comment by KvL159** [comment]
Sorry for duplicate !
