### ISSUE TITLE
Cannot properly wipe off all nocodb data

### ISSUE THREAD

**Issue by kpalik** [YunoHost-Apps/nocodb_ynh#84]
### Describe the bug

I installed nocodb some months ago, version 0.99.2. Then i clicked update from the admin panel. The update went ok, but it still shows 0.99.2 in top-left corner after update. After some weeks i clicked remove app and installed it again from scratch. The version is 0.99.2 even after creating new domain in Yunohost admin panel. 

ssh shows "version: 0.100.1~ynh1" but the app is lacking features from that version (e.g. QR Code column) and shows v0.99.2 in top-left corner

I am missing something (like deleting some cache from server, tha is not deleted by uninstalling the app from YH admin panel)?  

### Context

- Hardware: lenovo laptop with Debian 11
- YunoHost version: 11.0.11 (stable)
- I have access to my server: *Through SSH & direct access via keyboard / screen *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- If upgrading, current package version: in ssh it shows me "version: 0.100.1~ynh1" but it is lacking features from that version (e.g. QR Code column)

**Comment by tituspijean** [comment]
Can you share the installation log of your new NocoDB instance? There is #22 bug currently, but new installs should at least fetch the newest versions...

**Comment by kpalik** [comment]
Hi, 
1) the file is 4kB long 
2) can i send it to you via email or other non-public channel ? you can use https://palikowski.net/blog/mail/ to send me an email adress

**Comment by tituspijean** [comment]
You can use the "Share with YunoPaste" button from the webadmin, or with the command `yunohost log share 20230207-193129-app_install-nocodb` to upload the log. This makes sure to remove any personal information from the log. Open the `paste.yunohost.org` page, check so, and share the address of the page here.

**Comment by tituspijean** [comment]
Closing, for lack of feedback.

If there's a cache, it is client side. Try to delete your browser cache.
