### ISSUE TITLE
Add a mention to the `/dashboard` url somewhere

### ISSUE THREAD

**Issue by Xananax** [YunoHost-Apps/nocodb_ynh#99]
I lost a few hours trying to understand why nocodb was not working. I had it on `subdomain.domain.tld`,   but when I was trying to access it, I was instead getting my static site at `domain.tld`.

Cue a few hours of diving into nginx configs, reading logs and so on.

Actually, I only had to navigate to `/dashboard`. Requiring a URL by itself is not really a surprising behavior, however, that NocoDB decides to just serve whatever is found on the root domain is _very_ surprising. Other applications show you an "installation went well" page or "read the docs".

I suggest a mention to head to that URL should be added at least to this repository's README, or, better, to the app panel in the yunohost web admin.

**Comment by robin9991** [comment]
So this mention would be nice but this did not resolve my issue. I have it on tables.domain.com and can't access it via tables.domain.com/dashboard but this is the only solution indicated here. Any other tips how to make this work?

Specifically it just returns "Cannot GET /dashboard".

**Comment by Xananax** [comment]
Sorry but I didn't have to do anything as far as I remember, I installed the app and was able to access the dashboard. 

It's possible that in my attempts to make it work, I restarted the service and Nginx. Something like:
```
sudo systemctl restart nocodb
sudo systemctl restart nginx
```
See if it changes anything?

**Comment by tituspijean** [comment]
Redirection seems automatic now, feel free to reopen if needed.
